# Generated by Django 5.1.4 on 2024-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_feedback', models.TextField(blank=True, db_column='id_Feedback', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('created_at', models.TextField(blank=True, db_column='Created_at', null=True)),
                ('priority', models.TextField(blank=True, db_column='Priority', null=True)),
                ('created_by', models.TextField(blank=True, db_column='Created_by', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedbackvisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_feedbackvisibility', models.TextField(blank=True, db_column='id_FeedbackVisibility', null=True)),
                ('id_feedback', models.TextField(blank=True, db_column='id_Feedback', null=True)),
                ('id_users', models.TextField(blank=True, db_column='id_Users', null=True)),
                ('access_time', models.TextField(blank=True, db_column='Access_time', null=True)),
            ],
            options={
                'db_table': 'FeedbackVisibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forms', models.TextField(blank=True, db_column='id_Forms', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('created_by', models.TextField(blank=True, db_column='Created_by', null=True)),
                ('created_at', models.TextField(blank=True, db_column='Created_at', null=True)),
            ],
            options={
                'db_table': 'Forms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupmembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membership', models.TextField(blank=True, db_column='id_Membership', null=True)),
                ('id_users', models.TextField(blank=True, db_column='id_Users', null=True)),
                ('id_groups', models.TextField(blank=True, db_column='id_Groups', null=True)),
                ('is_leader', models.TextField(blank=True, db_column='is_Leader', null=True)),
            ],
            options={
                'db_table': 'GroupMembership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_groups', models.TextField(blank=True, db_column='id_Groups', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'Groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.TextField(blank=True, db_column='id_Role', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.TextField(blank=True, db_column='id_Users', null=True)),
                ('first_name', models.TextField(blank=True, db_column='First_name', null=True)),
                ('last_name', models.TextField(blank=True, db_column='Last_name', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('rating', models.TextField(blank=True, db_column='Rating', null=True)),
                ('role_id', models.TextField(blank=True, db_column='Role_id', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
