# Generated by Django 5.1.4 on 2025-05-27 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReview',
            fields=[
                ('id_feedback', models.AutoField(db_column='id_Feedback', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='User', max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', default=0)),
                ('review', models.CharField(db_column='Review', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at', null=True)),
            ],
            options={
                'db_table': 'Feedback_Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedbackvisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_feedbackvisibility', models.TextField(blank=True, db_column='id_FeedbackVisibility', null=True)),
                ('id_feedback', models.TextField(blank=True, db_column='id_Feedback', null=True)),
                ('id_user', models.TextField(blank=True, db_column='id_User', null=True)),
                ('access_time', models.TextField(blank=True, db_column='Access_time', null=True)),
            ],
            options={
                'db_table': 'FeedbackVisibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forms', models.TextField(blank=True, db_column='id_Forms', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('created_by', models.TextField(blank=True, db_column='Created_by', null=True)),
                ('created_at', models.TextField(blank=True, db_column='Created_at', null=True)),
            ],
            options={
                'db_table': 'Forms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_groups', models.TextField(blank=True, db_column='id_Groups', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'Groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.TextField(blank=True, db_column='id_Role', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupmembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membership', models.TextField(blank=True, db_column='id_Membership', null=True)),
                ('id_user', models.TextField(blank=True, db_column='id_User', null=True)),
                ('id_group', models.TextField(blank=True, db_column='id_Group', null=True)),
                ('is_leader', models.BooleanField(blank=True, db_column='is_Leader', null=True)),
            ],
            options={
                'db_table': 'GroupMembership',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaderPost',
            fields=[
                ('id_post', models.AutoField(db_column='id_Post', primary_key=True, serialize=False)),
                ('created_by', models.CharField(db_column='Created_by', max_length=50, null=True)),
                ('tag', models.CharField(db_column='Tag', max_length=50, null=True)),
                ('topic', models.CharField(db_column='Topic', max_length=50, null=True)),
                ('content', models.TextField(db_column='Content', null=True)),
            ],
            options={
                'db_table': 'Leader_Post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaderPollItem',
            fields=[
                ('id_item', models.AutoField(db_column='id_Item', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('votes', models.IntegerField(blank=True, db_column='Votes', default=0, null=True)),
                ('voters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('leader_post', models.ForeignKey(blank=True, db_column='Leader_post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_items', to='TeamReflectApp.leaderpost')),
            ],
            options={
                'db_table': 'Leader_Poll',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(db_column='id_Comment', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='Created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leader_poll_item', models.ForeignKey(blank=True, db_column='Leader_poll_item', null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamReflectApp.leaderpollitem')),
            ],
            options={
                'db_table': 'Comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(db_column='id_Feedback', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=50, null=True)),
                ('type', models.CharField(db_column='Type', max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at', null=True)),
                ('priority', models.CharField(db_column='Priority', max_length=50, null=True)),
                ('created_by', models.CharField(db_column='Created_by', max_length=50, null=True)),
                ('content', models.TextField(db_column='Content', null=True)),
                ('status', models.CharField(db_column='Status', max_length=50, null=True)),
                ('likes', models.IntegerField(blank=True, db_column='Likes', default=0)),
                ('for_group', models.ForeignKey(blank=True, db_column='For_Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('for_user', models.ForeignKey(blank=True, db_column='For_User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_post', models.ForeignKey(blank=True, db_column='For_Post', null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamReflectApp.leaderpost')),
            ],
            options={
                'db_table': 'Feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('leader_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TeamReflectApp.leaderpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('source_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User Note',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, db_column='Rating', default=0)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_leader', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User Profile',
                'managed': True,
            },
        ),
    ]
