# Generated by Django 5.1.4 on 2025-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamReflectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='likes',
            field=models.IntegerField(blank=True, db_column='Likes', default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(db_column='Title', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
