# Generated by Django 5.1.4 on 2025-01-26 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamReflectApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderpollitem',
            name='content',
            field=models.TextField(blank=True, db_column='Content', null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(db_column='id_Comment', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('created_by', models.ForeignKey(blank=True, db_column='Created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leader_poll_item', models.ForeignKey(blank=True, db_column='Leader_poll_item', null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamReflectApp.leaderpollitem')),
            ],
            options={
                'db_table': 'Comment',
                'managed': True,
            },
        ),
    ]
