# Generated by Django 5.1.4 on 2025-01-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamReflectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderPost',
            fields=[
                ('id_post', models.AutoField(db_column='id_Post', primary_key=True, serialize=False)),
                ('created_by', models.CharField(db_column='Created_by', max_length=50, null=True)),
                ('topic', models.CharField(db_column='Topic', max_length=50, null=True)),
                ('content', models.TextField(db_column='Content', null=True)),
            ],
            options={
                'db_table': 'Leader_Post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaderPollItem',
            fields=[
                ('id_item', models.AutoField(db_column='id_Item', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=150, null=True)),
                ('leader_post', models.ForeignKey(blank=True, db_column='Leader_post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_items', to='TeamReflectApp.leaderpost')),
            ],
            options={
                'db_table': 'Leader_Poll',
                'managed': True,
            },
        ),
    ]
