# Generated by Django 5.1.4 on 2025-01-18 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamReflectApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackreview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='feedback',
            name='for_group',
            field=models.ForeignKey(blank=True, db_column='For_Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='for_post',
            field=models.ForeignKey(blank=True, db_column='For_Post', null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamReflectApp.leaderpost'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='for_user',
            field=models.ForeignKey(blank=True, db_column='For_User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
