# Generated by Django 5.1.4 on 2025-05-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamReflectApp', '0002_leaderpollitem_voters_leaderpollitem_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('leader_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TeamReflectApp.leaderpost')),
            ],
        ),
    ]
