# Generated by Django 5.1.4 on 2025-01-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamReflectApp', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReview',
            fields=[
                ('id_feedback', models.AutoField(db_column='id_Feedback', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='User', max_length=50, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', default=0)),
                ('review', models.CharField(db_column='Review', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at', null=True)),
            ],
            options={
                'db_table': 'Feedback_Review',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, db_column='Rating', default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(blank=True, db_column='Rating', default=0),
        ),
    ]
